version: '3'
services:
    mongodb:
      image: mongo
      ports:
        - "27017:27017"

    mongo-seed:
      build: ./mongo-seed
      links:
        - mongodb


    api:
      build: ./app
      ports:
        - "5000:5000"
      volumes:
        - ./app:/app:rw
      depends_on:
        - mongodb

    ClinicalReportR:
      build: ../ClinicalReportR
      image: report
      volumes:
        - ../ClinicalReportR:/data
      network_mode: "host"
      depends_on:
        - api
        - mongodb